Add rabbitmq applications and add couple of files for Kafka
yevgenykuz/service-discovery-demo-parent pull request #18
Opened 2020-09-30 12:08 UTC by ofertavivcx

2020-09-30 17:29 UTC, yevgenykuz requested changes
Please consider my comments.

Other notes:
- No port for rabbitmq server?
- Can you please update Java README.md file too?

2020-09-30 17:29 UTC, yevgenykuz commented on java-apps/java-rabbitmq-http-entry-point/src/main/java/rabbitmqhttpentrypoint/controller/RabbitMQController.java
> + */
```suggestion
```

2020-09-30 17:29 UTC, yevgenykuz commented on java-apps/java-rabbitmq-entry-point/src/main/java/rabbitmqentrypoint/producer/Producer.java
> +        System.out.println("Sending message...");
Maybe this should print what message is being sent?

```suggestion
        System.out.println("Sending message... <" + new String(message) + ">");
```

2020-09-30 17:29 UTC, yevgenykuz commented on java-apps/java-rabbitmq-propagator/pom.xml
> +    <artifactId>java-rabbitmq-propagator</artifactId>
```suggestion
    <modelVersion>4.0.0</modelVersion>

    <artifactId>java-rabbitmq-propagator</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    
    <parent>
        <artifactId>service-discovery-demo-parent</artifactId>
        <groupId>com.checkmarx.demo.service.discovery</groupId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
```

2020-09-30 17:29 UTC, yevgenykuz commented on java-apps/java-rabbitmq-propagator/run.bat
> +java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=1011 -javaagent:"agent\cx-launcher.jar" -DcxAgentAutoUpgrade=no -Dcx.standalone=yes -Dcx.log.level=DEBUG -jar "target\java-rabbitmq-
```suggestion
java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8419 -javaagent:"agent\cx-launcher.jar" -DcxAgentAutoUpgrade=no -Dcx.standalone=yes -Dcx.log.level=DEBUG -jar "target\java-rabbitmq-propagator.jar"
```

2020-09-30 17:29 UTC, yevgenykuz commented on java-apps/java-rabbitmq-propagator/src/main/java/rabbitmqpropagator/BaseConfiguration.java
> +    }*/
Leftovers?

2020-09-30 17:29 UTC, yevgenykuz commented on java-apps/java-rabbitmq-propagator/src/main/java/rabbitmqpropagator/JavaRabbitMQPropagator.java
> +
```suggestion
```

2020-09-30 17:29 UTC, yevgenykuz commented on java-apps/java-rabbitmq-propagator/src/main/java/rabbitmqpropagator/producer/Producer.java
> +        System.out.println("Sending message...");
```suggestion
        System.out.println("Sending message... <" + new String(message) + ">");
```

2020-09-30 17:29 UTC, yevgenykuz commented on java-apps/java-rabbitmq-sink/pom.xml
> +    <artifactId>java-rabbitmq-sink</artifactId>
```suggestion
    <modelVersion>4.0.0</modelVersion>

    <artifactId>java-rabbitmq-sink</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    
    <parent>
        <artifactId>service-discovery-demo-parent</artifactId>
        <groupId>com.checkmarx.demo.service.discovery</groupId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
```

2020-09-30 17:29 UTC, yevgenykuz commented on java-apps/java-rabbitmq-sink/run.bat
> +java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=1011 -javaagent:"agent\cx-launcher.jar" -DcxAgentAutoUpgrade=no -Dcx.standalone=yes -Dcx.log.level=DEBUG -jar "target\java-rabbitmq-
```suggestion
java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8420 -javaagent:"agent\cx-launcher.jar" -DcxAgentAutoUpgrade=no -Dcx.standalone=yes -Dcx.log.level=DEBUG -jar "target\java-rabbitmq-sink.jar"
```

2020-09-30 17:29 UTC, yevgenykuz commented on java-apps/java-rabbitmq-sink/src/main/java/rabbitmqsink/BaseConfiguration.java
> +    }*/
Leftovers?

2020-09-30 17:29 UTC, yevgenykuz commented on java-apps/java-rabbitmq-sink/src/main/java/rabbitmqsink/JavaRabbitMQSink.java
> +
```suggestion
```

2020-09-30 17:29 UTC, yevgenykuz commented on java-apps/pom.xml
> +        <module>java-rabbitmq-http-entry-point</module>
```suggestion
        <module>java-rabbitmq-entry-point</module>
        <module>java-rabbitmq-http-entry-point</module>
        <module>java-rabbitmq-propagator</module>
        <module>java-rabbitmq-sink</module>
```

2020-10-01 06:29 UTC, ofertavivcx commented on java-apps/java-rabbitmq-sink/src/main/java/rabbitmqsink/BaseConfiguration.java
> +    }*/
yes,

2020-10-01 06:32 UTC, ofertavivcx commented on java-apps/java-rabbitmq-sink/src/main/java/rabbitmqsink/BaseConfiguration.java
> +    }*/
removed

2020-10-01 06:35 UTC, ofertavivcx commented on java-apps/java-rabbitmq-propagator/src/main/java/rabbitmqpropagator/BaseConfiguration.java
> +    }*/
yes, removed

2020-10-01 07:13 UTC, yevgenykuz requested changes

2020-10-01 07:13 UTC, yevgenykuz commented on README.rst
> +~~~~~
```suggestion
~~~~~~~~
```

2020-10-01 07:18 UTC, yevgenykuz approved these changes

2020-10-01 07:18 UTC, merged